### ISSUE TITLE
`parse-url` security vulnerabilities

### ISSUE THREAD

**Issue by tsteinke-iabbb** [zeplin/cli#102]
Hi!

Dependabot has flagged a couple of security vulnerabilities in our project with `parse-url`. It appears that the vulnerable version of this package is loaded through the `git-url-parse` dependency of  `@zeplin/cli`. 

From what I can tell, the latest update of `git-url-parse` includes a fix for these vulnerabilities.

Are you able to update this dependency to the latest version and publish an update to the npm package?

Thank you!

**Comment by yuqu** [comment]
I've prepared PRs to fix it. There is a breaking change on the mentioned package, I'll take one last look and test the patch ASAP before publishing it.

**Comment by tsteinke-iabbb** [comment]
Thanks for taking care of this so quickly!

It looks like the patch hasn't been published to npm yet. Are you able to do that so that we can update it in our project?

**Comment by yuqu** [comment]
@tsteinke-iabbb `@zeplin/cli@2.0.1` is published. 

I'm sorry for the delay. There were a couple of issues with other dependencies, I wanted to be sure if I could resolve all of the issues at once (yet I found out that we couldn't if we don't drop node@12 support)
