### ISSUE TITLE
CLI does not work with Yarn 3+

### ISSUE THREAD

**Issue by AbuHafsa** [zeplin/cli#113]
I tried to use the CLI on a project to create a component from Zeplin in my React component library and it failed to install the packages. I pinpointed the problem and it seems that the CLI checks for Yarn using `has-yarn` but does not consider if the Yarn version is v1 or v2. As Yarn introduced many breaking changes the following line would not work because `--ignore-workspace-root-check` is not a flag to be found in recent versions of Yarn.
https://github.com/zeplin/cli/blob/fc7486482c1e77a40ed642f8f9886287acf7b0c1/src/service/package-manager.ts#L52

I can submit a PR to fix this issue but I am unsure if the CLI has been abandoned as the latest version was released 2 years ago.

**Comment by yuqu** [comment]
Hi @AbuHafsa, I can gladly review and publish a new version if you could submit a PR.

**Comment by yuqu** [comment]
Thanks for the PR, I've published [v2.0.2](https://github.com/zeplin/cli/releases/tag/v2.0.2) 🎉
