### ISSUE TITLE
I set the token as env variable but error

### ISSUE THREAD

**Issue by carolirod** [zeplin/cli#26]
I created the token in my Profile in Zeplin,
then added it as environment-variable,
it recognized it but now I'm getting this error:
`Audience is not set in authentication token.`

but when creating the token there was no "audience option" 🤔 

> in my case it's connected with the google account at work so that's why I have to use the token

pd. I got very excited about this feature 🎉 !

**Comment by yuqu** [comment]
Hi, 

That's really weird, looks like it is more of a internal issue instead of CLI. Checking our backend might help us to understand and resolve the issue. Can you please send the email address of your Zeplin account and details about the issue support@zeplin.io?

**Comment by shortsn** [comment]
Hi,
i am having the same issue. :(

**Comment by joebui** [comment]
I'm having the same issue too.

**Comment by carolirod** [comment]
So to fix it >
In Profile go to "Connected Apps" > revoke the token and create a new one there > use that one for the CLI, and it works!
