### ISSUE TITLE
--help lists only two options

### ISSUE THREAD

**Issue by alexey-yacob-com** [zeplin/cli#28]
```bash
Zeplin CLI - v1.0.0

Usage: zeplin [options] [command]

Options:
  -V, --version      output the version number
  -h, --help         output usage information

Commands:
  connect [options]  Connect components to code
  login [options]    Login to Zeplin
```
https://github.com/zeplin/cli#usage
| Options      | Description                                       | Default                 |
|--------------|---------------------------------------------------|-------------------------|
| -f, --file   | Path to components configuration file             | .zeplin/components.json |
| -d, --dev    | Activate development mode                         | false                   |
| --no-watch   | Disable watching file changes on development mode | false                   |
| -p, --plugin | npm package name of a Zeplin CLI `connect` plugin |                         |
| -h, --help   | Output usage information                          |                         |
| --verbose    | Enable verbose logs                               |                         |

`PS: Meant to post this from my` @n3tn0de `account 😅`

**Comment by yuqu** [comment]
Hi Alexey,

This is actually intended. What you see there on the documentation is the output of `zeplin connect --help`. 

```
$ zeplin connect --help

Zeplin CLI - v1.0.0

Usage: zeplin connect [options]

Connect components to code

Options:
  -f, --file <file>      Full path to components file (default: [".zeplin/components.json"])
  -d, --dev              Activate development mode (default: false)
  --no-watch             Disable watch files on development mode
  -p, --plugin <plugin>  npm package name of a Zeplin CLI connect plugin (default: [])
  --verbose              Enable verbose logs
  -h, --help             output usage information
```

`zeplin --help` lists available commands which are `connect` and `login`.
