### ISSUE TITLE
Using Zeplin CLI while logged in with Google account.

### ISSUE THREAD

**Issue by botteu** [zeplin/cli#31]
Hi,

I'm trying to use the ´zeplin connect´ command to connect but I get a message saying:

`Access token not found in ZEPLIN_ACCESS_TOKEN environment variable.`

and then I'm prompted to input my user login credentials. I input my Google login (since this is what I use to log in) and I get the following error: 

`Username or password is incorrect - Please try again or reset your password from 'Forgot password?'.`

Can I set the access token somewhere?

Ragards,
Daniel

**Comment by yuqu** [comment]
Hi Daniel,

Users authenticated via any SSO (that is Google for you) should retrieve an access token from [Connected Apps](https://app.zeplin.io/profile/connected-apps`) page on Zeplin. After you get the token, set it as a environment variable using the command below.

For *NIX
```shell
export ZEPLIN_ACCESS_TOKEN=your-token-here
```

For Windows
```shell
set ZEPLIN_ACCESS_TOKEN=your-token-here
```

**Comment by botteu** [comment]
Figured it out. Thanks!
