### ISSUE TITLE
Absolute repository url

### ISSUE THREAD

**Issue by vitorcamachoo** [zeplin/cli#33]
When setting a private repository, eg. **http://gitlab.example.company.com**, it is setting on zeplin on the following way: **http://www.gitlab.com/http://gitlab.example.company.com**

**Comment by yuqu** [comment]
Hi,

Could you share your gitlab configuration?

```
...
    "gitlab": {
        "url": "http://gitlab.example.company.com",
        "repository": "example/react-components"
    }
...
```

**Comment by yuqu** [comment]
Closing the issue because of inactivity. Please reopen the issue if the problem persists.
