### ISSUE TITLE
wildcard match (*) for source => zeplin matches

### ISSUE THREAD

**Issue by alexkrolick** [zeplin/cli#36]
A lot of the time, one component maps onto several zeplin elements.

```jsonc
            "path": "src/components/input.js",
            "zeplinNames": [
                "Text Input/Valid",
                "Text Input/Error",
                //... a lot more here
            ]
```

It would be nice to be able to specify a wildcard match for the zeplin names:

```jsonc
            "path": "src/components/input.js",
            "zeplinNames": ["Text Input/*"]
```

This would allow additional states to be added in Zeplin without manually updating the config file for each one.

**Comment by XOP** [comment]
Have same idea,  
in our sketch setup naming can get pretty extensive matching just one React entity

**Comment by yuqu** [comment]
Hi, thanks for your feedback. 
We're currently working on an update to make wildcards work as you described. I'll notify you here once it is ready.

**Comment by yuqu** [comment]
You can now use wildcards on `zeplinNames`. Please check out https://github.com/zeplin/connected-components-docs/pull/20 for examples.
