### ISSUE TITLE
Incorrect bitbucket link generated

### ISSUE THREAD

**Issue by k33ny** [zeplin/cli#37]
Zeplin generates wrong BB links when connected.
Instead of `https://bitbucket.org/<repo>/src/<branch>/<pathToFile>` it generates `https://bitbucket.org/<repo>/<branch>/src/<pathToFile>` which is invalid on Bitbucket Cloud

**Comment by yuqu** [comment]
Hi @k33ny, thanks for your feedback. 

It is fixed in v1.0.1, please update `@zeplin/cli` on your environment and see if it works for you.
