### ISSUE TITLE
Bitbucket integration breaks with v1.0.1

### ISSUE THREAD

**Issue by shortsn** [zeplin/cli#39]
Hi,
we are using the bitbucket integration with our on premise instance (`Bitbucket v6.9.1`).
Even though bitbucket cloud and self hosted seem to have different url patterns we manged to get it running with the following configuration:
@zeplin/cli@1.0.0
"bitbucket": {
        "repository": "angular-components",
        "branch": "browse",
        "url": "https://SERVER/projects/PROJECT/repos"
    }

with `v1.0.0`
this produces a url like `https://SERVER/projects/PROJECT/repos/angular-components/browse/src/Component/component.ts`
This url points to the file on the default branch of the repository.

after updating to `v1.0.1` the generated url does no longer work and looks like `https://SERVER/projects/PROJECT/repos/angular-components/src/browse/src/Component/component.ts`

Am i using it wrong? How do i need to setup the connection to a self hosted bitbucket intance?

**Comment by yuqu** [comment]
Oops, looks like I messed up while fixing https://github.com/zeplin/cli/issues/37

I was thinking the [this document](
https://confluence.atlassian.com/bitbucket/hyperlinking-to-source-code-in-bitbucket-824476709.html) applies to both Cloud and Server version. Apparently, I was wrong. 

It seems there is no official documentation on Server hyperlinks but [here]( https://community.atlassian.com/t5/Bitbucket-questions/Bitbucket-Hyperlinking-to-source-code-in-Bitbucket/qaq-p/618967) someone from Atlassian team gives details about it.

I'll look into it ASAP.

**Comment by yuqu** [comment]
@shortsn v1.0.2 is now published. 

There are new fields for Bitbucket Server configuration to indicate which project/user does the repository belong to. You can use the following configuration.

```
"bitbucket": {
  "repository": "angular-components",
  "url": "https://SERVER",
  "project": "PROJECT"
}
```
`https://SERVER/projects/PROJECT/repos/angular-components/browse/src/Component/component.ts`

I've made sure that your existing workaround configuration to work as it is in v1.0.0. So you don't need to change anything.

**Comment by shortsn** [comment]
Hi, thank you very much. Will try it on Monday.
Have a nice weekend.

**Comment by shortsn** [comment]
Perfect, thanks.
