### ISSUE TITLE
Pipeline Issues

### ISSUE THREAD

**Issue by k33ny** [zeplin/cli#41]
zeplin connect exits with success code (0) even when there are errors when conecting. Please change this to exit(1) so the pipelines would be able to fail accordingly.

**Comment by yuqu** [comment]
Hi @k33ny,

The intended behavior is already using exit(1) on errors. [Another issue](https://github.com/zeplin/cli-connect-storybook-plugin/issues/21) is opened today about a similar problem. I'm working on it. 

Could you also share the following?
- The error output when you receive exit(0) (with `--verbose` if possible)?
- What plugins do you use?

**Comment by k33ny** [comment]
This can be closed as it's an exact duplicate of #21
