### ISSUE TITLE
npm : axios dependency SSRF vulnerability 

### ISSUE THREAD

**Issue by Nino3103** [zeplin/cli#69]
Hello ! 

First, I would like to thank you for zeplin-cli, Connected Components is an awesome feature ! 👏 

Recently, I ran into a problem coming from the axios dependency of  @zeplin/cli ("axios": "^0.19.0").
npm is warning me about a potential high vulnerability (SSRF vulnerability) coming from axios package before 0.21.1 : https://www.npmjs.com/advisories/1594

Is it a problem for my app ? Should I worry about it ? 

Thanks in advance

**Comment by yuqu** [comment]
Hey, I'll release an hotfix today to address dependency vulnerability reports. Thanks for reaching out.

**Comment by Nino3103** [comment]
Thank you !

**Comment by yuqu** [comment]
Fixed by https://github.com/zeplin/cli/pull/68
