### ISSUE TITLE
Feature Request: support linking specific zeplin ID/name to specific story

### ISSUE THREAD

**Issue by bsinibaldi** [zeplin/cli#88]
My company is utilizing zeplin in combination with storybook to link directly to stories for each component variant. As an example, let's say we have a `Button` component with several variants:
- Button / Primary / Large
- Button / Primary / Small
- Button / Secondary / Large
- Button / Secondary / Small

For each of these Zeplin components, we have a corresponding story. These stories are all for the same React component (as they're just a `Button` component with different properties).

Currently, per the documentation we'd set the `components.json` up something like this:
```json
"components": [
  {
    "name": "Button",
    "path": "libraries/components/Button.tsx",
    "zeplinNames": [
      "Button / Primary / Large",
      "Button / Primary / Small",
      "Button / Secondary / Large",
      "Button / Secondary / Small"
    ]
  }
]
```
When linking these via the `zeplin connect` command, each zeplin component _does_ get linked to the stories. The issue is that the "Open in Storybook" link in the sidebar in Zeplin itself links directly to the _first_ story, rather than the appropriate story for that variant (all of the linked stories _are_ available in a dropdown menu, but we feel that's a bit counterintuitive, especially because the story names might not line up exactly with the zeplin names)

In an attempt to work around this (and following the documentation for the [storybook plugin](https://github.com/zeplin/connected-components-docs/blob/master/docs/link/STORYBOOK.md)) we adjusted the `components.json` file to manually specify stories and zeplin names like so:
```json
"components": [
  {
    "name": "Button",
    "path": "libraries/components/Button.tsx",
    "storybook": {
      "kind": "Button",
      "stories": [
        "large-primary",
        "small-primary",
        "large-secondary",
        "small-secondary"
      ]
    },
    "zeplinNames": [
      "Button / Primary / Large",
      "Button / Primary / Small",
      "Button / Secondary / Large",
      "Button / Secondary / Small"
    ]
  }
]
```
This, however, achieved the same result (as a side note, I also tried each of the above patterns with specific zeplin IDs instead of just zeplin names, but that also achieved the same result).

I was finally able to get the desired functionality in place by forking this package and making the following change to the `src/commands/connect/plugin.ts` file:
```ts
    // okay, assumption time here - if we have a connected component with multiple zeplin names/ids
    // we're going to assume that there is a story link for each name/id
    const finalConnectedComponents: ConnectedComponent[] = [];
    connectedComponents.forEach(component => {
        const storyLinks = component.urlPaths?.filter(({ type }) => type === LinkType.storybook) || [];
        const remainingLinks = component.urlPaths?.filter(({ type }) => type !== LinkType.storybook) || [];
        // if we have multiple stories, we assume that each zeplin name corresponds to a single story
        // and that both the stories and the zeplin names arrays are in the same order
        // note that this was done to avoid having to modify the ConnectedComponent config type
        if (storyLinks.length > 1) {
            storyLinks.forEach((storyLink, index) => {
                if (component.zeplinNames && component.zeplinNames[index]) {
                    finalConnectedComponents.push({
                        ...component,
                        zeplinNames: [component.zeplinNames[index]],
                        urlPaths: [storyLink, ...remainingLinks]
                    });
                } else if (component.zeplinIds && component.zeplinIds[index]) {
                    finalConnectedComponents.push({
                        ...component,
                        zeplinIds: [component.zeplinIds[index]],
                        urlPaths: [storyLink, ...remainingLinks]
                    });
                }
            });
        } else {
            finalConnectedComponents.push(component);
        }
    });
```
The above code is meant to act as a starting point for a discussion into potentially adding official support to this library for linking a specific Zeplin ID/Name to a specific story.

**Comment by dantailby** [comment]
I am having the same issue, it would be really nice to see this functionality in the main repo.

**Comment by yuqu** [comment]
Hi, thanks for the suggestion. I believe it could work for some users while it could be a breaking change for others. The other problem is that it only works for manual story configuration. 

We were already evaluating potential changes to cover a story link for each component case. One of the solutions is about leveraging `zeplinLink`s of `storybook-zeplin` addon to determine which story belongs to which component. Another solution is that Zeplin client apps might sort the links on the story dropdown menu based on the most common words as a workaround, I think it would resolve the issue for most of the projects. Both options are not planned yet, but I will keep you updated once we have a plan.

**Comment by bsinibaldi** [comment]
Thanks for the response! I want to first reiterate that the code I posted was meant to start discussion only, and was not meant to illustrate a possible solution (it would indeed be a breaking change for a lot of use cases). 

The fact that it requires manual story configuration is not, in my humble opinion, a problem. The proposed solution of using `zeplinLink`s is effectively the same, no? To utilize `storybook-zeplin`, you have to _manually_ specify zeplin links for a given story. And if we're going to be doing manual configuration anyway, wouldn't it make more sense to keep one source of truth (the `components.json` file) as opposed to having to now go to each story file individually?

With regards to the menu sorting in client apps: while I have no issue with that behavior being added, I do not think it qualifies as a solution to this problem. it might alleviate this issue in some cases, but it still wouldn't do what this feature request is asking, which is to link a single, _specific_ story to a single _specific_ zeplin component.

**Comment by yuqu** [comment]
> The fact that it requires manual story configuration is not, in my humble opinion, a problem. The proposed solution of using `zeplinLink`s is effectively the same, no? To utilize `storybook-zeplin`, you have to _manually_ specify zeplin links for a given story. And if we're going to be doing manual configuration anyway, wouldn't it make more sense to keep one source of truth (the `components.json` file) as opposed to having to now go to each story file individually?

The details are not yet finalized but the initial thought is to keep all Connected Components config in stories, without keeping a set of `components` in `components.json` file. Or even using `storybook-addon` itself to manage Connected Components without `@zeplin/cli` to make things easier.

**Comment by bsinibaldi** [comment]
> The details are not yet finalized but the initial thought is to keep all Connected Components config in stories, without keeping a set of components in components.json file. Or even using storybook-addon itself to manage Connected Components without @zeplin/cli to make things easier for Storybook users.

Ahhh I see, I like that. This sounds like an excellent solution, if there's anything I can do to assist please let me know
